/*** Generated by streamline.js - DO NOT EDIT ***/
var test_error = new Error();
exports.test = function(next, assert) {
    f(function(err, result) {
        assert.equal(err, test_error);
        next();
    });
};
function f(callback) {
    try {
        result3 = (g() + 1);
    } catch (err) {
        if (callback) {
            return callback(err)
        } else {
            throw err
        };
    };
};
function g() {
    throw test_error;
};
